import{useEffect,useMemo,useRef,useState}from"react";import{BUILDINGS,UPGRADES,cost,GameState,load,save,clickPower,totalBuildings,rates,initial,fireCost,assigned,populationCap,nextPopCost,JobId}from"./game";import{AGE_REQUIREMENTS,ITEMS,RECIPES,RESOURCES,ItemId}from"./data";import{Brain,Clock3,Flame,Pickaxe,RotateCcw,Sparkles,Zap,LockKeyhole,ChevronRight,Trophy,MousePointer2,ArrowRight,Users,Hammer,PackageOpen,Crown}from"lucide-react";
const fmt=(n:number)=>n>=1e6?(n/1e6).toFixed(2)+"M":n>=1e3?(n/1e3).toFixed(1)+"K":Math.floor(n).toLocaleString("tr-TR");
const JOBS=[["forager","Toplayıcı","🍖"],["woodcutter","Oduncu","🪵"],["miner","Madenci","⛏️"],["scholar","Bilgin","🧠"]] as const;
export default function App(){const[s,setS]=useState<GameState>(()=>load());const ref=useRef(s);const[floats,setFloats]=useState<{id:number,v:number,x:number,y:number}[]>([]);useEffect(()=>{ref.current=s},[s]);const r=useMemo(()=>rates(s),[s]);const buildings=totalBuildings(s),free=s.population-assigned(s),fc=fireCost(s);
useEffect(()=>{const t=setInterval(()=>setS(x=>{const q=rates(x),dt=.1;const discovered=RECIPES.filter(z=>x.knowledge>=z.unlockKnowledge).map(z=>z.id);return{...x,food:x.food+q.food*dt,wood:x.wood+q.wood*dt,stone:x.stone+q.stone*dt,fiber:x.fiber+q.fiber*dt,knowledge:x.knowledge+q.knowledge*dt,discovered:[...new Set([...x.discovered,...discovered])],lastTick:Date.now(),combo:Date.now()-x.comboAt>1800?0:x.combo}}),100);return()=>clearInterval(t)},[]);useEffect(()=>{const t=setInterval(()=>save(ref.current),2000);return()=>clearInterval(t)},[]);
const gather=(e:React.MouseEvent)=>setS(x=>{const now=Date.now(),chain=now-x.comboAt<900?Math.min(25,x.combo+1):1,cm=1+chain*(x.upgrades.includes("embers")?.02:.01),crit=Math.random()<.05,p=Math.floor(clickPower(x)*cm*(crit?4:1));setFloats(f=>[...f.slice(-8),{id:now,v:p,x:e.clientX,y:e.clientY}]);setTimeout(()=>setFloats(f=>f.filter(z=>z.id!==now)),750);return{...x,food:x.food+p,clicks:x.clicks+1,combo:chain,comboAt:now}});
const buy=(id:any)=>setS(x=>{const b=BUILDINGS.find(z=>z.id===id)!;if(totalBuildings(x)<b.unlock)return x;const c=cost(b,x.buildings[id]);return x.food<c?x:{...x,food:x.food-c,buildings:{...x.buildings,[id]:x.buildings[id]+1}}});
const job=(id:JobId,d:number)=>setS(x=>{if(d>0&&x.population-assigned(x)<=0)return x;if(d<0&&x.jobs[id]<=0)return x;return{...x,jobs:{...x.jobs,[id]:x.jobs[id]+d}}});
const recruit=()=>setS(x=>{const c=nextPopCost(x);return x.population<populationCap(x)&&x.food>=c?{...x,food:x.food-c,population:x.population+1}:x});
const upgradeFire=()=>setS(x=>{const c=fireCost(x);return x.food>=c.food&&x.stone>=c.stone&&x.wood>=c.wood?{...x,food:x.food-c.food,stone:x.stone-c.stone,wood:x.wood-c.wood,fireLevel:x.fireLevel+1}:x});
const research=(id:string,c:number)=>setS(x=>x.knowledge>=c&&!x.upgrades.includes(id)?{...x,knowledge:x.knowledge-c,upgrades:[...x.upgrades,id]}:x);
const craft=(recipe:any)=>setS(x=>{const req=recipe.requires as Record<string,number>;for(const[k,v]of Object.entries(req)){const have=(x as any)[k]??(x.inventory as any)[k]??0;if(have<v)return x}const n:any={...x,inventory:{...x.inventory}};for(const[k,v]of Object.entries(req)){if(k in n)n[k]-=v;else n.inventory[k]-=v}n.inventory[recipe.out]+=recipe.qty;return n});
const canAge=s.knowledge>=AGE_REQUIREMENTS.knowledge&&s.population>=AGE_REQUIREMENTS.population&&s.fireLevel>=AGE_REQUIREMENTS.fireLevel&&Object.entries(AGE_REQUIREMENTS.items).every(([k,v])=>s.inventory[k as ItemId]>=v);
const ageUp=()=>{if(canAge&&confirm("Taş Devri tamamlandı. Antik Çağ'a geçilsin mi?"))setS(x=>({...x,age:1}))};
return <main>{floats.map(f=><span className="float" style={{left:f.x,top:f.y}} key={f.id}>+{fmt(f.v)} 🍖</span>)}<header><div><span className="eyebrow">TIME EMPIRE · {s.age?"ANTİK ÇAĞ":"TAŞ DEVRİ"}</span><h1>{s.age?"Şafağın Şehri":"İlk Ateş"}</h1><p>Kaynak üret · insanlarını yönet · eşya üret · medeniyet kur.</p></div><div className="era"><Clock3/> {s.age?"ANTİK ÇAĞ":"TAŞ DEVRİ"} <span>0{s.age+1}</span></div></header>
<section className="resources"><Card n="Yiyecek" icon="🍖" v={s.food} rate={r.food}/><Card n="Odun" icon="🪵" v={s.wood} rate={r.wood}/><Card n="Taş" icon="🪨" v={s.stone} rate={r.stone}/><Card n="Lif" icon="🌿" v={s.fiber} rate={r.fiber}/><Card n="Bilgi" icon="🧠" v={s.knowledge} rate={r.knowledge}/></section>
<div className="hero"><div className="world"><div className="stars"/><div className="mountains"/><div className="settlement"><button className="fire" onClick={gather}><span className={"flame f"+Math.min(5,s.fireLevel)}>🔥</span><b>ATEŞİ BESLE · SV.{s.fireLevel}</b><small>+{fmt(clickPower(s))} yiyecek · %5 kritik</small></button></div><div className="combo">{s.combo>1&&<>COMBO ×{s.combo}</>}</div></div><div className="mission firepanel"><small>KAMP ATEŞİ</small><h3>Seviye {s.fireLevel} → {s.fireLevel+1}</h3><p>Her seviye tıklamayı ve tüm üretimi güçlendirir.</p><div className="costline"><span>{fmt(fc.food)} 🍖</span><span>{fmt(fc.wood)} 🪵</span><span>{fmt(fc.stone)} 🪨</span></div><button disabled={s.food<fc.food||s.wood<fc.wood||s.stone<fc.stone} onClick={upgradeFire}>ATEŞİ GELİŞTİR <ArrowRight/></button></div></div>
<div className="three"><section className="panel people"><small>NÜFUS & İŞ GÜCÜ</small><h2>{s.population} İnsan <em>{free} boşta</em></h2><div className="jobgrid">{JOBS.map(j=><div className="job" key={j[0]}><span>{j[2]} <b>{j[1]}</b></span><div><button onClick={()=>job(j[0],-1)}>−</button><strong>{s.jobs[j[0]]}</strong><button disabled={free<=0} onClick={()=>job(j[0],1)}>+</button></div></div>)}</div><button className="wide" disabled={s.population>=populationCap(s)||s.food<nextPopCost(s)} onClick={recruit}><Users/> Yeni İnsan · {fmt(nextPopCost(s))} 🍖 <span>{s.population}/{populationCap(s)}</span></button></section>
<section className="panel"><small>ENVANTER & CRAFTING</small><h2>Eşya Üretimi</h2><div className="inventory">{Object.entries(ITEMS).map(([id,it])=><span key={id}>{it.icon} {it.name}<b>{s.inventory[id as ItemId]}</b></span>)}</div><div className="recipes">{RECIPES.map(q=>{const unlocked=s.discovered.includes(q.id);return <div className={"recipe "+(!unlocked?"locked":"")} key={q.id}><div><b>{unlocked?ITEMS[q.out].icon:"🔒"} {unlocked?q.name:"Bilinmeyen Tarif"}</b><small>{unlocked?Object.entries(q.requires).map(([k,v])=>{const rr=(RESOURCES as any)[k],ii=(ITEMS as any)[k];return (rr?.icon||ii?.icon)+" "+v}).join("  +  "):q.unlockKnowledge+" Bilgi ile keşfedilir"}</small></div><button disabled={!unlocked} onClick={()=>craft(q)}><Hammer/></button></div>})}</div></section>
<section className="panel ageproject"><small>BÜYÜK PROJE</small><h2>Antik Çağ'a Geçiş</h2><p>Yeni çağı açmak için medeniyetinin kendi kendine yetebildiğini kanıtla.</p><Req ok={s.inventory.settlementCore>=1} t="🗿 Yerleşim Anıtı" v={s.inventory.settlementCore+"/1"}/><Req ok={s.inventory.stoneAxe>=3} t="🪓 Taş Balta" v={s.inventory.stoneAxe+"/3"}/><Req ok={s.inventory.huntingKit>=2} t="🏹 Av Takımı" v={s.inventory.huntingKit+"/2"}/><Req ok={s.inventory.cutStone>=20} t="🧱 Yontulmuş Taş" v={s.inventory.cutStone+"/20"}/><Req ok={s.knowledge>=1800} t="🧠 Bilgi" v={fmt(s.knowledge)+"/1.8K"}/><Req ok={s.population>=18} t="👥 Nüfus" v={s.population+"/18"}/><Req ok={s.fireLevel>=5} t="🔥 Kamp Ateşi" v={s.fireLevel+"/5"}/><button className="agebtn" disabled={!canAge||s.age>0} onClick={ageUp}><Crown/>{s.age?"ANTİK ÇAĞ AÇILDI":"ÇAĞI BAŞLAT"}</button></section></div>
<div className="layout"><section><div className="title"><div><small>YERLEŞİM</small><h2>Üretim Yapıları</h2></div><span>{buildings} yapı</span></div><div className="grid">{BUILDINGS.map(b=>{const locked=buildings<b.unlock,c=cost(b,s.buildings[b.id]);return <article className={"building "+(locked?"locked":"")} key={b.id}><div className="bi">{locked?<LockKeyhole/>:b.icon}</div><div className="grow"><div className="row"><h3>{b.name}</h3><b>Lv. {s.buildings[b.id]}</b></div><p>{locked?b.unlock+" toplam yapı gerekli":b.desc}</p><button disabled={locked||s.food<c} onClick={()=>buy(b.id)}>{locked?"Kilitli":"İnşa et"} {!locked&&<span>{fmt(c)} 🍖</span>}</button></div></article>})}</div></section><aside><div className="panel"><small>ARAŞTIRMA</small><h2>Teknoloji</h2>{UPGRADES.map(u=><div className={"upgrade "+(s.upgrades.includes(u.id)?"done":"")} key={u.id}><b>{u.icon} {u.name}</b><p>{u.desc}</p><button disabled={s.knowledge<u.cost||s.upgrades.includes(u.id)} onClick={()=>research(u.id,u.cost)}>{s.upgrades.includes(u.id)?"Tamamlandı":u.cost+" 🧠 Araştır"}<ChevronRight/></button></div>)}</div><div className="panel prestige"><small>ZAMAN DÖNGÜSÜ</small><h2>Prestige</h2><p>Çağ ilerledikçe zaman döngüsü açılacak.</p><button disabled><RotateCcw/> Kilitli</button></div></aside></div>
<footer><span><i/> Yerel kayıt aktif</span><button onClick={()=>{if(confirm("Bütün ilerleme silinsin mi?")){localStorage.removeItem("time-empire-save");setS(initial())}}}>Kaydı sıfırla</button></footer></main>}
function Card({n,icon,v,rate}:{n:string,icon:string,v:number,rate:number}){return <div className="card"><div className="ico">{icon}</div><div><small>{n}</small><strong>{fmt(v)}</strong><span>+{fmt(rate)}/sn</span></div></div>}function Req({ok,t,v}:{ok:boolean,t:string,v:string}){return <div className={"req "+(ok?"ok":"")}><span>{ok?"✓":"○"} {t}</span><b>{v}</b></div>}