import{ItemId}from"./data";
export type BuildingId="hut"|"farm"|"lumber"|"gatherer"|"mine"|"workshop";export type JobId="forager"|"woodcutter"|"miner"|"scholar";
export type GameState={food:number;wood:number;stone:number;fiber:number;knowledge:number;shards:number;population:number;buildings:Record<BuildingId,number>;jobs:Record<JobId,number>;inventory:Record<ItemId,number>;discovered:string[];upgrades:string[];lastTick:number;startedAt:number;clicks:number;combo:number;comboAt:number;frenzyUntil:number;fireLevel:number;age:number};
export const BUILDINGS=[
{id:"hut" as BuildingId,name:"Toplayıcı Kampı",icon:"⛺",desc:"Barınak ve nüfus kapasitesi.",base:90,unlock:0},
{id:"farm" as BuildingId,name:"Yabani Tarla",icon:"🌾",desc:"Toplayıcıların yiyecek verimini artırır.",base:520,unlock:2},
{id:"lumber" as BuildingId,name:"Oduncu Alanı",icon:"🪵",desc:"Odun üretimini güçlendirir.",base:900,unlock:4},
{id:"gatherer" as BuildingId,name:"Lif Toplama Alanı",icon:"🌿",desc:"Doğal lif toplar.",base:1350,unlock:6},
{id:"mine" as BuildingId,name:"Taş Ocağı",icon:"⛏️",desc:"Madencilerin taş üretimini artırır.",base:2300,unlock:8},
{id:"workshop" as BuildingId,name:"İlkel Atölye",icon:"⚒️",desc:"Bilginin ve crafting'in merkezi.",base:6200,unlock:11}] as const;
export const UPGRADES=[{id:"tools",name:"Keskin Taş Aletler",icon:"🪨",desc:"İşçi üretimi +%25",cost:180},{id:"hands",name:"Usta Eller",icon:"✋",desc:"Ateş tıklaması ×2",cost:500},{id:"embers",name:"Kor Ateş",icon:"🔥",desc:"Combo etkisi ×2",cost:1200}] as const;
export const initial=():GameState=>({food:30,wood:0,stone:0,fiber:0,knowledge:0,shards:0,population:2,buildings:{hut:0,farm:0,lumber:0,gatherer:0,mine:0,workshop:0},jobs:{forager:2,woodcutter:0,miner:0,scholar:0},inventory:{rope:0,timber:0,cutStone:0,stoneAxe:0,huntingKit:0,settlementCore:0},discovered:[],upgrades:[],lastTick:Date.now(),startedAt:Date.now(),clicks:0,combo:0,comboAt:0,frenzyUntil:0,fireLevel:1,age:0});
export const totalBuildings=(s:GameState)=>Object.values(s.buildings).reduce((a,b)=>a+b,0);export const assigned=(s:GameState)=>Object.values(s.jobs).reduce((a,b)=>a+b,0);
export const cost=(b:(typeof BUILDINGS)[number],n:number)=>Math.floor(b.base*Math.pow(1.23,n));export const fireCost=(s:GameState)=>({food:Math.floor(240*Math.pow(2.05,s.fireLevel-1)),stone:Math.floor(20*Math.pow(1.8,Math.max(0,s.fireLevel-2))),wood:Math.floor(25*Math.pow(1.7,Math.max(0,s.fireLevel-1)))});
export const mult=(s:GameState)=>1+s.shards*.1+(s.upgrades.includes("tools")?.25:0)+(s.fireLevel-1)*.06;
export const rates=(s:GameState)=>{const m=mult(s)*(Date.now()<s.frenzyUntil?2:1);return{food:s.jobs.forager*(1.05+s.buildings.farm*.18)*m,wood:s.jobs.woodcutter*(.75+s.buildings.lumber*.16)*m,stone:s.jobs.miner*(.52+s.buildings.mine*.13)*m,fiber:(s.buildings.gatherer*.28+s.jobs.forager*.08)*m,knowledge:s.jobs.scholar*(.2+s.buildings.workshop*.09)*m}};
export const clickPower=(s:GameState)=>Math.max(1,Math.floor((1+s.fireLevel*1.3)*(s.upgrades.includes("hands")?2:1)*(1+s.shards*.1)));
export const populationCap=(s:GameState)=>4+s.buildings.hut*3;export const nextPopCost=(s:GameState)=>Math.floor(140*Math.pow(1.32,Math.max(0,s.population-2)));
export const load=():GameState=>{try{const raw=localStorage.getItem("time-empire-save");if(!raw)return initial();const base=initial(),old=JSON.parse(raw),s={...base,...old,buildings:{...base.buildings,...old.buildings},jobs:{...base.jobs,...old.jobs},inventory:{...base.inventory,...old.inventory}};const sec=Math.min(Math.max(0,(Date.now()-s.lastTick)/1000),8*3600),r=rates(s);s.food+=r.food*sec;s.wood+=r.wood*sec;s.stone+=r.stone*sec;s.fiber+=r.fiber*sec;s.knowledge+=r.knowledge*sec;s.lastTick=Date.now();return s}catch{return initial()}};export const save=(s:GameState)=>localStorage.setItem("time-empire-save",JSON.stringify({...s,lastTick:Date.now()}));